import { FileHelper, z } from '@start9labs/start-sdk'
import { sdk } from '../sdk'

const shape = z.object({
  // `CAMOFOX_ACCESS_KEY` bearer token. Generated on install; re-generated by
  // the rotate-access-key action. Read reactively in both main.ts (daemon env)
  // and interfaces.ts (proxy auth gate) so a rotation restarts the container
  // and re-keys the proxy edge in one pass. Human-unfriendly but presented
  // copyable by the view-access-key action.
  accessKey: z.string().optional().catch(undefined),
})

export const storeJson = FileHelper.json(
  { base: sdk.volumes.main, subpath: 'store.json' },
  shape,
)
